/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.practice1.Practice1;

import java.io.IOException;
import java.util.concurrent.ExecutionException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException, IOException {
//        Practice1.runCode();
//        Practice2.runCode();
//        Practice3.runCode();
        Practice4SpringApp.main(new String[] {});
    }
}
