/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "РКСП"
include("app")
include("practice1")
include("practice2")
include("practice3")
include("practice4")
include("practice5")
include("practice5:practice5-s3-minio")
findProject(":practice5:practice5-s3-minio")?.name = "practice5-s3-minio"
include("practice5:practice5-eureka-server")
findProject(":practice5:practice5-eureka-server")?.name = "practice5-eureka-server"
include("practice5:practice5-s3-server")
findProject(":practice5:practice5-s3-server")?.name = "practice5-s3-server"
include("practice5:practice5-nginx")
findProject(":practice5:practice5-nginx")?.name = "practice5-nginx"
include("practice7")
