spring.application.name: config-server
server.port: 8888
spring.cloud.config.server.git:
  search-paths:
    - cloud-configs
  clone-on-start: true
  default-label: master
  private-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
  uri: git@github.com:lexa2hk/term-7-rksp.git
  ignore-local-ssh-settings: true

eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/
spring:
  cloud:
    config:
      enabled: false
